In [3]:
import pandas as pd

In [14]:
police_us=pd.read_csv("C:/Users/Amministratore/Gitlearning/corso-ifoa-machine-learning/Abanob-Ayat/shootings.csv")
police_us

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,Asian,Shelton,WA,True,attack,Not fleeing,False,Guns
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,White,Aloha,OR,False,attack,Not fleeing,False,Guns
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,Hispanic,Wichita,KS,False,other,Not fleeing,False,Unarmed
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,White,San Francisco,CA,True,attack,Not fleeing,False,Other unusual objects
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,Hispanic,Evans,CO,False,attack,Not fleeing,False,Piercing objects
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,5916,Rayshard Brooks,2020-06-12,shot,Taser,27.0,M,Black,Atlanta,GA,False,attack,Foot,True,Electrical devices
4891,5925,Caine Van Pelt,2020-06-12,shot,gun,23.0,M,Black,Crown Point,IN,False,attack,Car,False,Guns
4892,5918,Hannah Fizer,2020-06-13,shot,unarmed,25.0,F,White,Sedalia,MO,False,other,Not fleeing,False,Unarmed
4893,5921,William Slyter,2020-06-13,shot,gun,22.0,M,White,Kansas City,MO,False,other,Other,False,Guns
4894,5924,Nicholas Hirsh,2020-06-15,shot,gun,31.0,M,White,Lawrence,KS,False,attack,Car,False,Guns

In [15]:
print(police_us.shape)

(4895, 15)

In [30]:
police_us.set_index(["name" , "armed"]).count(level="name")

,id,date,manner_of_death,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category
name,,,,,,,,,,,,,
Austin Wilburly Reid,1,1,1,1,1,1,1,1,1,1,1,1,1
A'Donte Washington,1,1,1,1,1,1,1,1,1,1,1,1,1
A.B. Carr,1,1,1,1,1,1,1,1,1,1,1,1,1
Aaron Allen Przekop,1,1,1,1,1,1,1,1,1,1,1,1,1
Aaron Bailey,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zepp Crouchet,1,1,1,1,1,1,1,1,1,1,1,1,1
Zhonghua Li,1,1,1,1,1,1,1,1,1,1,1,1,1
Zoe Dowdell,1,1,1,1,1,1,1,1,1,1,1,1,1
Zonell Williams,1,1,1,1,1,1,1,1,1,1,1,1,1
Zyon Romeir Wyche,1,1,1,1,1,1,1,1,1,1,1,1,1

In [31]:
police_us.loc[0, :]

id                                   3
name                        Tim Elliot
date                        2015-01-02
manner_of_death                   shot
armed                              gun
age                                 53
gender                               M
race                             Asian
city                           Shelton
state                               WA
signs_of_mental_illness           True
threat_level                    attack
flee                       Not fleeing
body_camera                      False
arms_category                     Guns
Name: 0, dtype: object

In [32]:
police_us.loc[[0, 1, 2,], :]

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,Asian,Shelton,WA,True,attack,Not fleeing,False,Guns
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,White,Aloha,OR,False,attack,Not fleeing,False,Guns
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,Hispanic,Wichita,KS,False,other,Not fleeing,False,Unarmed

In [42]:
police_us.loc[0:10, 'race':'state']

        race           city state
0      Asian        Shelton    WA
1      White          Aloha    OR
2   Hispanic        Wichita    KS
3      White  San Francisco    CA
4   Hispanic          Evans    CO
5      White        Guthrie    OK
6   Hispanic       Chandler    AZ
7      White        Assaria    KS
8      White     Burlington    IA
9      Black      Knoxville    PA
10     White       Stockton    CA

In [45]:
police_us[police_us.city=='San Francisco']

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,White,San Francisco,CA,True,attack,Not fleeing,False,Other unusual objects
140,182,Amilcar Perez-Lopez,2015-02-26,shot,knife,21.0,M,Hispanic,San Francisco,CA,False,other,Not fleeing,False,Sharp objects
198,221,Alice Brown,2015-03-17,shot,unknown,24.0,F,White,San Francisco,CA,True,other,Not fleeing,False,Unknown
761,922,Herbert Benitez,2015-10-15,shot,gun,27.0,M,Hispanic,San Francisco,CA,False,attack,Not fleeing,False,Guns
833,998,Javier Lopez Garcia,2015-11-11,shot,gun,25.0,M,Hispanic,San Francisco,CA,False,attack,Not fleeing,False,Guns
888,1052,Mario Woods,2015-12-02,shot,knife,26.0,M,Black,San Francisco,CA,False,other,Not fleeing,False,Sharp objects
1233,1443,Luis Gongora,2016-04-07,shot,knife,45.0,M,Hispanic,San Francisco,CA,False,other,Not fleeing,False,Sharp objects
1330,1548,Jessica Nelson-Williams,2016-05-19,shot,unarmed,29.0,F,Black,San Francisco,CA,False,other,Car,False,Unarmed
1703,1970,Nicholas McWherter,2016-10-14,shot,gun,26.0,M,White,San Francisco,CA,True,attack,Not fleeing,False,Guns
2202,2556,Nicholas Flusche,2017-05-03,shot,knife,26.0,M,White,San Francisco,CA,False,attack,Not fleeing,True,Sharp objects
2248,2603,John Eno,2017-05-23,shot,gun,59.0,M,White,San Francisco,CA,False,other,Not fleeing,False,Guns
2565,2975,Damien Murray,2017-09-24,shot,gun,39.0,M,Black,San Francisco,CA,False,other,Not fleeing,True,Guns
2737,3176,Keita O'Neil,2017-12-01,shot,unarmed,42.0,M,Black,San Francisco,CA,False,other,Car,True,Unarmed
2964,3478,Jesus Delgado-Duarte,2018-03-06,shot,gun,19.0,M,Hispanic,San Francisco,CA,False,attack,Not fleeing,False,Guns
3010,3534,Jehad Eid,2018-03-21,shot,gun,21.0,M,Asian,San Francisco,CA,False,attack,Not fleeing,False,Guns

In [48]:
police_us[police_us.city=='San Francisco'].race

3          White
140     Hispanic
198        White
761     Hispanic
833     Hispanic
888        Black
1233    Hispanic
1330       Black
1703       White
2202       White
2248       White
2565       Black
2737       Black
2964    Hispanic
3010       Asian
Name: race, dtype: object

In [55]:
police_us[police_us.city=='San Francisco'].state

3       CA
140     CA
198     CA
761     CA
833     CA
888     CA
1233    CA
1330    CA
1703    CA
2202    CA
2248    CA
2565    CA
2737    CA
2964    CA
3010    CA
Name: state, dtype: object

In [56]:
police_us.iloc[:, [0,7]]

        id      race
0        3     Asian
1        4     White
2        5  Hispanic
3        8     White
4        9  Hispanic
...    ...       ...
4890  5916     Black
4891  5925     Black
4892  5918     White
4893  5921     White
4894  5924     White

[4895 rows x 2 columns]

In [65]:
police_us.index

RangeIndex(start=0, stop=4895, step=1)

In [85]:
police_us[police_us["body_camera"]=='False']

KeyError: 'body_camera'

In [86]:
police_us["body_camera"]==False

KeyError: 'body_camera'

In [74]:
police_us.index

RangeIndex(start=0, stop=4895, step=1)

In [84]:
police_us.body_camera.value_counts()["False"]

AttributeError: 'DataFrame' object has no attribute 'body_camera'